# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"

bold_font        auto
italic_font      auto
bold_italic_font auto
background #0f0f0f
# END_KITTY_FONTS

font_size 18.0

# KEY MOD
kitty_mod alt

background_opacity 1

map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

map ctrl+minus font_size_decrease
map ctrl+equal font_size_increase
map ctrl+0 font_size_reset

enable_audio_bell false

hide_window_decorations no

clipboard_control write-clipboard read-clipboard write-primary read-primary

include themes/cyberdream.conf
